name: Run Cypress E2E Tests

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    env:
      CYPRESS_baseUrl: ${{ secrets.CYPRESS_BASEURL }}
      CYPRESS_testUserEmail: ${{ secrets.CYPRESS_TESTUSEREMAIL }}
      CYPRESS_testUserPassword: ${{ secrets.CYPRESS_TESTUSERPASSWORD }}
      CI: true
      CYPRESS_VIDEO: true
      CYPRESS_VIDEO_COMPRESSION: 20
      CYPRESS_VIDEO_UPLOAD_ON_PASS: false
      CYPRESS_SCREENSHOT_ON_RUN_FAILURE: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check Cypress install
        run: npx cypress verify

      #  Run all specs in one Cypress process in given order
      - name: Run Cypress E2E Tests Sequentially
        run: |
          npx cypress run --browser chrome --headless --spec "cypress/e2e/**/*.cy.js"

      #  Merge mochawesome JSON into single file
      - name: Merge Mochawesome JSON
        run: npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/report.json

      #  Generate HTML report from merged JSON
      - name: Generate Mochawesome HTML Report
        run: npx marge cypress/reports/mochawesome/report.json -f report -o cypress/reports/mochawesome

      #  Upload artifacts: Videos, Screenshots, Reports
      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
            cypress/reports/
          retention-days: 1