name: Run Cypress E2E Tests (Dynamic Parallel, Exclude One Spec)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  discover-specs:
    runs-on: ubuntu-latest
    outputs:
      specs: ${{ steps.set-specs.outputs.specs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Cypress spec files (excluding fn-full-flow)
        id: set-specs
        run: |
          specs=$(find cypress/e2e -name "*.cy.js" \
            ! -path "cypress/e2e/Facility-Network/fn-full-flow.cy.js" \
            | sort | jq -R -s -c 'split("\n")[:-1]')
          echo "Discovered specs: $specs"
          echo "specs=$specs" >> $GITHUB_OUTPUT

  e2e-tests:
    needs: discover-specs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(needs.discover-specs.outputs.specs) }}

    env:
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
      FN_EMAIL: ${{ secrets.FN_EMAIL }}
      FN_PASSWORD: ${{ secrets.FN_PASSWORD }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      CI: true
      CYPRESS_VIDEO: true
      CYPRESS_VIDEO_COMPRESSION: 20
      CYPRESS_VIDEO_UPLOAD_ON_PASS: false
      CYPRESS_SCREENSHOT_ON_RUN_FAILURE: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress for ${{ matrix.spec }}
        run: |
          echo "Running spec: ${{ matrix.spec }}"
          npx cypress run --browser chrome --headless \
            --spec "${{ matrix.spec }}" \
            --reporter mochawesome \
            --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,json=true

      - name: Upload Mochawesome JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-${{ matrix.spec }}
          path: cypress/reports/mochawesome/*.json

  merge-report:
    runs-on: ubuntu-latest
    needs: e2e-tests

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: cypress/reports/mochawesome

      - name: Merge Mochawesome JSON
        run: npx mochawesome-merge "cypress/reports/mochawesome/**/*.json" > cypress/reports/mochawesome/report.json

      - name: Generate Mochawesome HTML Report
        run: npx marge cypress/reports/mochawesome/report.json -f report -o cypress/reports/mochawesome

      - name: Upload Final Combined Report
        uses: actions/upload-artifact@v4
        with:
          name: combined-cypress-report
          path: cypress/reports/mochawesome
          retention-days: 7
